#Application Environment Properties
environmentContext:
  inDevMode: ${IN_DEV}
  originalUrlName: url
  shortUrlKeyName: tinyurl

#Server Properties
server:
  port: ${APPLICATION_PORT}
  address: ${APPLICATION_HOST}

#Application Properties
spring:
  application:
    name: tinyurl
  cache:
    type: redis
  config:
    import: optional:file:dev.env[.properties]
  datasource:
    username: ${POSTGRES_HOST_USER}
    password: ${POSTGRES_HOST_PASSWORD}
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/postgres
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    ssl: false
    user: ${REDIS_HOST_USER}
    timeout: 2000ms
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_HOST_PASSWORD}
#   url: "redis://user:tinyurl@cache123@localhost:1112"
